spring:
  profiles:
    active: local
  main:
    allow-bean-definition-overriding: true
  ai:
    openai:
      base-url: https://api.siliconflow.cn
      chat:
        options:
          model: deepseek-ai/DeepSeek-V3
          tool-calling:
            enabled: true
        completions-path: /v1/chat/completions
server:
  port: 8080
# JWT配置
jwt:
  secret: MySecretKeyForJWT2025!@#$%^&*()_+SecureKeyHere
  expiration: 86400000
  refresh-expiration: 604800000
  header: Authorization
  token-prefix: "Bearer "
